language: generic
services:
  - docker

before_install:
  - chmod +x deploy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1

jobs:
  include:
    - stage: "Scratch"
      script: ./deploy oscartbeaumont/scratch scratch/
