language: generic
services:
  - docker

before_install:
  - chmod +x deploy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || exit 1

script: if [ $TRAVIS_EVENT_TYPE = cron ]; then ./deploy rebuild-all; else ./deploy; fi
